site_name: Aqsam
repo_url: https://github.com/Samy-Y/Aqsam
site_description: Aqsam is an open-source school management system built with Flask.
site_author: Samy Y
copyright: MIT License
nav:
  - Home: index.md
  - Features: features.md
  - Usage: usage.md
  - Models: models.md
  - Database: database_schema.md
  - Services: service_functions.md
